version: '2'

services:
  web:
    restart: always
    build: ./web/
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - ./web:/data/web
      - ./logs:/data/logs
    entrypoint: /data/web/docker-entrypoint.sh

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - .env
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

volumes:
    db_data:
